### ISSUE TITLE
Ensure that getorganizedbk.org email forwarders are working properly.

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#1]
When sending an email to digital@getorganizedbk.org, error message reads: 

![screen shot 2018-08-25 at 9 55 38 am](https://user-images.githubusercontent.com/28609124/44619217-c1f97000-a850-11e8-9d49-9a1f08e35b9e.png)

"Delivery incomplete
There was a temporary problem delivering your message to Digital@getorganizedbk.org. Gmail will retry for 44 more hours. You'll be notified if the delivery fails permanently."

Need to ensure that these three are working: 
Info@getorganizedbk.org to  getorganizedbk@gmail.com
Digital@getorganizedbk.org to anniehirshman@gmail.com 
Webmaster@getorganizedbk.org to joelrputnam@gmail.com

Email forwarders were recently moved to GoDaddy, here: 
My Products > Domains > getorganizedbk.org > Manage > Add email
https://sso.godaddy.com/?regionsite=www&realm=idp&app=wcc&path=email&marketid=en-US

**Comment by getorganizedbk** [comment]
@anniehirshman I'm not seeing any trouble with these in GoDaddy. 

Have you tried emailing without capitalizing?

IE digital@getorganizedbk.org

**Comment by anniehirshman** [comment]
I tried sending an email to myself earlier today (without caps), and didn't receive it, unfortunately.  Not sure how to troubleshoot from here!

**Comment by anniehirshman** [comment]
Update: received the following additional error: 

<img width="1036" alt="screen shot 2018-08-27 at 1 44 48 pm" src="https://user-images.githubusercontent.com/28609124/44675799-7afdad00-a9ff-11e8-8440-905a6d684150.png">

LEARN MORE directs to: https://support.google.com/mail/answer/6596?visit_id=636709886796973800-1527285231&rd=1

**Comment by anniehirshman** [comment]
Verified that this is also an issue for digital@getorganizedbk.org (no caps).

**Comment by adibben** [comment]
@anniehirshman GoDaddy needed us to setup the MX records to connect with their email forwarder. 

They are now connected and will take 2-48 hours to start working. Support ballparked 2hours, but said at the most 48hrs. I'm going to close this issue and if we see it pop up again we can open it up again!

**Comment by anniehirshman** [comment]
@adibben ok thanks so much!!  doesn't seem to be working yet, but will try again tomorrow
