### ISSUE TITLE
Upgrade to the latest version of Divi.

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#16]
On the staging environment, need to upgrade website to the latest version of Divi using the active license key, and ensure that the upgrade does not break the current design.

For more details and to help, contact @anniehirshman

**Comment by adibben** [comment]
<img width="1198" alt="screenshot 2018-09-25 16 21 42" src="https://user-images.githubusercontent.com/5303492/46040737-28d3a880-c0df-11e8-82ce-38a24abcc11f.png">

@anniehirshman can you renew the account so we can upgrade please?

**Comment by anniehirshman** [comment]
@adibben unfortunately, we can't renew this account, because the subscription belongs to the first dev who set up the site and is unresponsive. 

We do have another volunteer who has provided his lifetime subscription to use his account instead!  So as part of completing this upgrade, we need to switch over to using his account/license.  Alvar had started this process but did not complete it. 

I'll send all the background info, so you have all the information, login, API key etc., in case someone else is able to tackle this.  Thanks!!
