### ISSUE TITLE
Add email address for Safety Net Defenders working group page.

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#18]
Add email address (dying4care@gmail.com) and email icon to Safety Net Defenders working group page.  

Match design and placement to other working group pages. Ex: https://getorganizedbk.org/indivisible-nation-bk/

**Comment by adibben** [comment]
@anniehirshman Where is the icon for email that you would like used on the page located? Can it be pulled from the other page?

**Comment by anniehirshman** [comment]
@adibben yep, this is from another page:

`<img class="alignnone size-full wp-image-3262" style="float: left;" src="https://getorganizedbk.wpengine.com/wp-content/uploads/2018/06/fa-envelope-square.png" alt="" width="31" height="31" />`

Or can import and style from the media library (file URL: http://getorganizedbk.org/wp-content/uploads/2018/06/fa-envelope-square.png)

**Comment by anniehirshman** [comment]
Closing issue because Safety Net Defenders is going inactive.
