### ISSUE TITLE
Groups dropdown menu is not scrollable on desktop.

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#19]

**Comment by anniehirshman** [comment]
On the top nav, the 'Groups' dropdown menu has so many groups that it is now cut off on many smaller laptop screens.  

Because the nav sticks to the top on scroll, and the menu itself does not have an internal scroll, it is impossible to navigate to the last options in the menu.

NOTE: the top nav is not sticky on mobile, so this is not an issue. 

<img width="719" alt="screen shot 2018-11-19 at 1 25 39 pm" src="https://user-images.githubusercontent.com/28609124/48727007-0487da00-ebff-11e8-92c8-4a45aebb4b2d.png">

**Comment by adibben** [comment]
@anniehirshman This is not a problem anymore @anniehirshman ?

**Comment by anniehirshman** [comment]
@adibben volunteers fixed this last HackNight by: 
Dropdown css revised: max-height and overflow parameters added (in Appearance > Custom CSS)

So this is technically solved.  If anyone's got a better solution, feel free to re-open the ticket!  Another suggestion was to categorize/reorg the nav menu, but I'm not sure how to do that with our current structure, since the working groups aren't really split into categories.
