### ISSUE TITLE
Remove Not In Our City and Safety Nets working groups from getorganizedbk.org.

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#23]
Two working groups are going inactive: Not In Our City and Safety Net Defenders.  

We need to update the website to reflect these changes.

Steps to complete:
1) In Appearance > Menus, remove both working groups from Header and Working Groups (footer) menus.  

2) In Pages > Home, in the Working Groups module on home page, remove thumbnail image and button for both working groups.  Then reshuffle placement of other working group thumbnails and buttons to fill in the gaps. 

3) In Pages, set 'Not In Our City' and 'Safety Net Defenders' pages to "Draft" status. 

Will ticket removing both working groups from the /Join form separately.

**Comment by JpTiger** [comment]
1. Done
2. Done  (though it's not pretty. There's no pretty way I know of to display 13 somethings)
3. Done

They'll be missed. Especially Safety Net Defenders, one of the O(w)G's.
