### ISSUE TITLE
Getorganizedbk.org redirects to getorganizedbk.wpengine.com

### ISSUE THREAD

**Issue by anniehirshman** [GetOrganizedBrooklyn/getorganizedbk-website#8]
Currently, getorganizedbk.org redirects to getorganizedbk.wpengine.com.  

Getorganizedbk.wpengine.com should not display to the end user - instead, all pages on the site should use the primary URL, getorganizedbk.org.

**Comment by adibben** [comment]
UNGH, I thought I already fixed this one. I'll check in again.

**Comment by anniehirshman** [comment]
@adibben thanks!  It doesn't look like it's working at the moment, not sure if you've had a chance to check it yet?  Is it also related to the MX records?
